services:
  mystocki-database: 
    image: postgres:latest 
    container_name: mystocki-database 
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - mystocki_postgres_data:/var/lib/postgresql/data
    networks:
      - mystocki-network

  web-project:
    hostname: "${PROJECT_NAME}.localhost"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/project
    command: [
      "sh",
      "-c",
      "python manage.py runserver ${RUNSERVER_HOST:-${PROJECT_NAME}.localhost}:${PORT}"
    ]
    volumes:
      - ./project/:/usr/src/project
    ports:
      - "${EXTERNAL_PORT:-${PORT}}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
      - DEBUG=true
    env_file:
      .env
    depends_on:
      - mystocki-database
    networks:
      - mystocki-network

networks:
    mystocki-network:
        external: true

volumes:
    mystocki_postgres_data: