services:
  mystocki-database: 
    image: postgres:latest 
    container_name: mystocki-database 
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - mystocki-network

  web-project:
    hostname: "${PROJECT_NAME}.localhost"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/project
    command: [
      "sh",
      "-c",
      "curl -fsSL https://deb.nodesource.com/setup_21.x | bash - && \
      apt-get install -y nodejs && \
      npm install && \
      pip install debugpy && \
      python -m debugpy --wait-for-client --listen 0.0.0.0:3000 \
      manage.py runserver ${PROJECT_NAME}.localhost:${PORT}"
    ]
    volumes:
      - ./project/:/usr/src/project
    ports:
      - "${PORT}:${PORT}"
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
      - DEBUG=true
    env_file:
      .env
    depends_on:
      - mystocki-database
    networks:
      - mystocki-network

networks:
    mystocki-network:
        external: true